# Generated by Django 3.2.4 on 2021-06-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_IP',
            fields=[
                ('ip_address', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
