# Generated by Django 3.2.4 on 2021-06-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_sekolah',
            fields=[
                ('npsn', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=500)),
                ('distrik', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('telp', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='List_IP',
        ),
    ]
