# Generated by Django 3.2.4 on 2021-06-12 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_list_pendaftar'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_pendaftar',
            name='tujuan',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
