# Generated by Django 3.2.4 on 2021-06-12 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_list_pendaftar_tujuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_pendaftar',
            name='last_update',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
