# Generated by Django 3.2.4 on 2021-06-12 04:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_list_pendaftar_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_pendaftar',
            name='nilai',
            field=models.CharField(default=datetime.datetime(2021, 6, 12, 4, 37, 54, 955027, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
