# Generated by Django 3.2.4 on 2021-06-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_list_pendaftar_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_pendaftar',
            name='last_update',
            field=models.DateField(auto_now=True, verbose_name='date_published'),
        ),
    ]
