# Generated by Django 3.2.4 on 2021-06-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_list_pendaftar_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_pendaftar',
            name='pic',
        ),
    ]
