# Generated by Django 3.2.4 on 2021-06-12 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_list_pendaftar_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_pendaftar',
            name='register',
            field=models.DateField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
