# Generated by Django 3.2.4 on 2021-06-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_list_pendaftar_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_pendaftar',
            name='ket',
            field=models.CharField(default='', max_length=1),
        ),
    ]
